language: clojure
lein: 2.8.1
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - make $TARGET
env:
  matrix:
    - VERSION=1.7 TARGET=test
    - VERSION=1.8 TARGET=test
    - VERSION=1.9 TARGET=test
  global:
    - secure: "BhXYh0WHTAzxFTEJHepjb3iBCRUiN+vvCKm8P0G89ZeuJIZ4wfI0lFxA46KPMFe42w4hFUYdrhoV5/BcUE16o1F/OThBIEmTuF4KaKjBaBBGkZuOOMdkgbXCAeiqrY97D/Stxwq0k/udYYm3VtzWb+RBXEgM+jxbTg8We4csl1R4uDoEZKbqF25PaJNMLfxcH9e94XpZDlSfJmqKkr/s9HrH+X5lnPLx5g2/MJLk1O96UDQwSSoX94wQerMDRDFBEXD2DOlNgYi4bkWGoCBkIgzyS5haCSohi/gxhnJkZXOExkjFiLYibK0nqA6tRdK9TdETTjTPpPVojO9R76WxaSQwsWEQevGGnDmDfX/WUYHpLBGRVUl47GlQ+KA05lQtkqH5Gs87qsw7ItHq43uE3AsdoWrZCHzKeumlBExz/stx59sWX888F/AOo0fRVh+HAMCMkkl2R6NQoT8IAOszpjl0V4SDeLx7i+SvMKuMC/gsk859O1PmJN6CS7x4x0Y7iTA+eRnKYxwkJIzZMiaWfV7IZmnHWN6C8lU7al0yRmUWKJhTnl6ysuN7r1ceY4NSnZDgibjUH94b4lu2YRjXdTyQgnlfSfsPsoSRb1dcZul4XWQKdRt+pcZgW2yToRUKA4lBA2NK3yLyHVf8lZ2OTMYMGgRXUrU8AJ7r8c3n5kM="
    - secure: "FjWsaYElco5BM3MeBxU7O00JBWjIccadpGLPzW2frx1ridDemJjOQ+J2z3UBfQkhI5q5Hc9p2lnozmbKl2Lz91krZH2akVtL/91t0XFJTmIQNjbHr8T4ErIMA78Ol1lfJAsMUenZUXORu2HUVeP5kbQdkgBfcP4cCOrsEYKurcrp9+aZhYkjIKheAc6yHGmIwd0M4C1YlGFEREwuTAGE0bMyQodp154o6LNyQmDii+vTPGGyz7YPGrXH3+UQ9+T5WQKse+ztghwIsqwy03fMvme0VLwKrgywcV2ewy+fOzAzHVx6LvDbY5W5rw9lsu+7NIlEpQ90cgXEdMQSHYjr1v97QomSfAVZUNYE6o7LQ7/wtv5Dxmhg6f+IeRnGUOFQI9smSSGbiyWaim2BJ9Xv4309n8jHhb7+klfX8cBM9PZVm3EvUh+e4xfSi/hjluA4wneXXtPsCUkztAtexo5rh3PDrqq+Aotuy4Mh7BL+dO6BKLT2sqc9daZqAnDHb0tYvJXclT95nbEtWS5dmrj17Nl12ajl1tH1zeG7cJbserPNVn5qvpsGjLMF6pZUqKp/pBanHUJOlYSbcJsTho08SedihU5NBLKcRg9vr7PcesA2WN7m2Yaqjt24QOLTHzPg8JKp0qzA1f5gjmXuzZBjFc28W5I/dZzJO45axZ+cqig="
    - secure: "W+o4EJf1yNsuKWqHTQF1QcWHLUKXzN1ERngXdPK+QbRx6IVIjs9DvDm+PEnIepJxLSxZednR/GXayrjW6h2GPwDs3vHmhj0mvTpyMWELLO3/jYbll5n/RInUNDYA3Zc8P7+E1lrix/7VR8urSPrrT2ShzzvkHcgtOGO83wlYlNnavqMlvw6Bw7oZsGKgtpsqvF/WheQ01k+tJZHvnitflWMrwYGt6QJFyExs2aKhIug80ZgzqHKsz1ET7ZKfZSPO0zSrAJlJM72NJ+XZbwpWbDcbYB/ENNsqEM1AywD+dYf3Aw6JsOyuDdCIJ1mOKa26q1/5977COUvxIq6aHjxxTE+OAgNBQaHeYNxduUEE4pjtuWPZuiiiMGMd4UxI1gEKXL13nM5W5DNIuWbN8BNWwDedsXxTiF3ZNdk/e6iRZtf/FyA344/aQNYX7GiDDPIJ7NumP8wMeLK8Z/cKwnKSqqXJE+SrILGDC35g/TDnhKRgl1LTNORyik9vDj7Tur7sYfM4M1F9vLFDmF7vddoqyrcx1LwxyYgoAKwVegIJl9FInn51jRL4KFYAS4VGe7PwliUWYDzHs2SmCnRWhgCdeNS5PI9GWi36qiCLBK41gp+OAI/j+m9w2rpBxisfqz/YMw8nzjE2+mh79TKEkSCNj/QUX7aI1yKbUvbnDBf2s78="
    - secure: "Kj9e6zoDmhmlwTLBnBReV8sxfDZN22JG5IcgjfTyOUhcL1vEIvtV52ltxK1U4RQn2ZdLNCLfKPoSXwJvmqcfe12sNkGj3ouQ2NiSyC64q5eXcSVmw/60ChBJhTlb8OnIgP5WSjxAoX/78iVmAkdZXThcNLdzw8UsmpYiMgyDMKNQ6eDUPoIRnA1QYYm80UcYF43EFqxMMb9X6iwLiuGBUes9+D6Uaja55KUEz/BrFKmbcMdCFFuOMP9ItL425o9Be76qItr1wj4jh3jg7hqxOyxW7I0i4Ygr38kb3AOTWNIIb3km+P9ibhaDyVjBL4dK/BCFLr9KTF0MQbmQ2wBgFdUCKv7Iz5+avnQqJHOJsCHfPlhSNGUv7eZTr4cvH1MsgpAC6rknjLJla6lQZSouoqmi8bmpNTEu1HvcLtniYR/BbZcUA2nJqbfZfdDLFGHfIHHtC3xjx82Fqxl+0JqqGfBYkCgLAcvbQIGMR8uhfwrxSGmIrZbRQ41PAQNmI2o/lCpyI/jPS5Q9SwhgLy0mjfNhjrF4iEoku46IR8vdwBrDFE5bJVtKJQ13OeHSCApgVG8DcW0dcWq+OTt65sji9TexHpcMJwxUAFiRmCRtG73KR5hCl7pJ1YOyR4X3Fgwsm6dhXLjLPXIhkC0UVhupBUFQAfxaFQOMqLSNVMBy9xQ="
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
stages:
  - name: check
  - name: test
  # Deploy only from the home repo where the credentials can be
  # properly decrypted. Never deploy from a pull request job.
  # In addition, ensure we're on the master branch (snapshots)
  # or a branch with semver naming (releases).
  - name: deploy
    if: repo = clojure-emacs/orchard
        AND type != pull_request
        AND ( branch = master OR branch =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ )
jobs:
  include:
    # Test latest OpenJDK against latest Clojure stable
    - env: VERSION=1.9 TARGET=test
      jdk: openjdk8

    # Test Clojure master against a single JDK
    - env: VERSION=master TARGET=test
      jdk: oraclejdk8

    # Coverage analysis
    - env: VERSION=1.9 TARGET=cloverage
      jdk: oraclejdk8
      after_success: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

    # Eastwood linter
    - stage: check
      env: VERSION=1.9 TARGET=eastwood
      jdk: oraclejdk8

    # Check cljfmt
    - stage: check
      env: VERSION=1.9 TARGET=cljfmt
      jdk: oraclejdk8

    # Deploy documentation
    - stage: deploy
      env: TARGET=docs
      jdk: oraclejdk8

    # Deploy artifacts
    - stage: deploy
      env: TARGET=deploy
      jdk: oraclejdk8

  fast_finish: true      # don't wait for allowed failures before build finish
  allow_failures:
    - env: VERSION=master TARGET=test
    - env: VERSION=1.9 TARGET=cloverage

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/14f0f7b4d5b20a70d032
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: never     # options: [always|never|change] default: always
